version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: aevum-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aevum_db
      POSTGRES_USER: aevum
      POSTGRES_PASSWORD: aevum_secret
    ports:
      - "5432:5432"
    volumes:
      - aevum_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aevum -d aevum_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3
    container_name: aevum-localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=0
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - aevum_localstack_data:/var/lib/localstack
      - ./infra/localstack-init.sh:/etc/localstack/init/ready.d/init-aws.sh
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  aevum_pg_data:
    driver: local
  aevum_localstack_data:
    driver: local
