spring:
  application:
    name: Aevum

  datasource:
    url: jdbc:postgresql://localhost:5432/aevum_db
    username: aevum
    password: aevum_secret
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://enjoyed-airedale-42.clerk.accounts.dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

aws:
  s3:
    bucket: aevum-storage-bucket
    region: us-east-1
    # Para dev local com LocalStack, defina: aws.s3.endpoint=http://localhost:4566
    # Em produção, remova a linha abaixo (será null e o SDK usará AWS real)
    endpoint: http://localhost:4566

---
# Profile de Dev Local (LocalStack)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/aevum_db
    username: aevum
    password: aevum_secret

aws:
  s3:
    endpoint: http://localhost:4566
    access-key: test
    secret-key: test
